// facultyData.js
const facultyData = {
  dsa: {
    theory: [
      { slot: "E2+TE2", venue: "PRP330", faculty: "ATHIRA K", type: "TH" },
      { slot: "E1+TE1", venue: "PRP330", faculty: "ATHIRA K", type: "TH" },
      { slot: "E1+TE1", venue: "PRP334", faculty: "MURALI S", type: "TH" },
      { slot: "E2+TE2", venue: "PRP333", faculty: "GOPINATH M.P", type: "TH" },
      { slot: "E2+TE2", venue: "PRP332", faculty: "GOVINDA K", type: "TH" },
      { slot: "E2+TE2", venue: "PRP334", faculty: "GAYATHRI P", type: "TH" },
      { slot: "E1+TE1", venue: "PRP332", faculty: "SARAVANAN R", type: "TH" },
      { slot: "E1+TE1", venue: "PRP339", faculty: "KALAAVATHI B", type: "TH" },
      { slot: "E2+TE2", venue: "PRP339", faculty: "VARALAKSHMI M", type: "TH" },
      { slot: "E1+TE1", venue: "PRP371", faculty: "ILANTHENRAL K P S K", type: "TH" },
      { slot: "E2+TE2", venue: "PRP371", faculty: "ILANTHENRAL K P S K", type: "TH" },
      { slot: "E2+TE2", venue: "PRP372", faculty: "JENICKA S", type: "TH" },
      { slot: "E2+TE2", venue: "PRP379", faculty: "IYAPPAN P", type: "TH" },
      { slot: "E2+TE2", venue: "PRP464", faculty: "KARTHIK G M", type: "TH" },
      { slot: "E1+TE1", venue: "SJT604", faculty: "NITHYA N S", type: "TH" },
      { slot: "E2+TE2", venue: "PRP472", faculty: "BERLIN M A", type: "TH" },
      { slot: "E2+TE2", venue: "PRP569", faculty: "KANAGARAJ K", type: "TH" },
      { slot: "E2+TE2", venue: "PRP471", faculty: "NITHYA N S", type: "TH" },
      { slot: "E1+TE1", venue: "PRP372", faculty: "JENICKA S", type: "TH" },
      { slot: "E1+TE1", venue: "PRP378", faculty: "RAJA S P", type: "TH" },
      { slot: "E2+TE2", venue: "PRP378", faculty: "RAJA S P", type: "TH" },
      { slot: "E1+TE1", venue: "PRP379", faculty: "IYAPPAN P", type: "TH" },
      { slot: "E1+TE1", venue: "PRP464", faculty: "KARTHIK G M", type: "TH" },
      { slot: "E2+TE2", venue: "PRP465", faculty: "BADRINATH N", type: "TH" },
      { slot: "E1+TE1", venue: "PRP465", faculty: "BADRINATH N", type: "TH" },
      { slot: "E1+TE1", venue: "PRP472", faculty: "BERLIN M A", type: "TH" },
      { slot: "E1+TE1", venue: "PRP569", faculty: "KANAGARAJ K", type: "TH" },
      { slot: "E1+TE1", venue: "PRP568", faculty: "ANINDITA KUNDU", type: "TH" },
      { slot: "E2+TE2", venue: "PRP568", faculty: "ANINDITA KUNDU", type: "TH" },
      { slot: "E1+TE1", venue: "PRP575", faculty: "SHALINI L", type: "TH" },
      { slot: "E1+TE1", venue: "PRP576", faculty: "SRIVANI A", type: "TH" },
      { slot: "E2+TE2", venue: "PRP575", faculty: "SHALINI L", type: "TH" },
      { slot: "E2+TE2", venue: "PRP576", faculty: "SRIVANI A", type: "TH" },
      { slot: "E2+TE2", venue: "PRP677", faculty: "SRIDHAR RAJ S", type: "TH" },
      { slot: "E1+TE1", venue: "PRP670", faculty: "ANURADHA G", type: "TH" },
      { slot: "E2+TE2", venue: "PRP670", faculty: "ANURADHA G", type: "TH" },
      { slot: "E1+TE1", venue: "PRP671", faculty: "JAGALINGAM P", type: "TH" },
      { slot: "E1+TE1", venue: "PRP677", faculty: "SRIDHAR RAJ S", type: "TH" },
      { slot: "E1+TE1", venue: "PRP678", faculty: "PRABIN S M", type: "TH" },
      { slot: "E2+TE2", venue: "PRP678", faculty: "PRABIN S M", type: "TH" },
      { slot: "E1+TE1", venue: "PRP772", faculty: "VETRISELVI T", type: "TH" },
      { slot: "E2+TE2", venue: "PRP772", faculty: "VETRISELVI T", type: "TH" },
      { slot: "E1+TE1", venue: "PRP766", faculty: "DURGESH KUMAR", type: "TH" },
      { slot: "E1+TE1", venue: "PRP773", faculty: "SIVAPRASAD DARLA", type: "TH" },
      { slot: "E2+TE2", venue: "PRP766", faculty: "SHARIEF BASHA S", type: "TH" },
      { slot: "E2+TE2", venue: "PRP773", faculty: "AYYASAMY.S", type: "TH" },
      { slot: "E1+TE1", venue: "PRP333", faculty: "SUBRAMANYAM REDDY", type: "TH" },
      { slot: "E2+TE2", venue: "PRP671", faculty: "JAGALINGAM P", type: "TH" },
      { slot: "E1+TE1", venue: "PRP230", faculty: "NALLIAH M", type: "TH" },
      { slot: "E2+TE2", venue: "PRP230", faculty: "PRAVEEN KUMAR G", type: "TH" }
    ],
    lab: [
      { slot: "L35+L36", venue: "PRP231", faculty: "SRIDHAR RAJ S", type: "LO" },
      { slot: "L53+L54", venue: "PRP232", faculty: "SUBRAMANYAM REDDY", type: "LO" },
      { slot: "L27+L28", venue: "PRP135", faculty: "GOPINATH M.P", type: "LO" },
      { slot: "L5+L6", venue: "PRP231", faculty: "IYAPPAN P", type: "LO" },
      { slot: "L45+L46", venue: "PRP231", faculty: "IYAPPAN P", type: "LO" },
      { slot: "L11+L12", venue: "PRP231", faculty: "PRABIN S M", type: "LO" },
      { slot: "L33+L34", venue: "PRP231", faculty: "PRABIN S M", type: "LO" },
      { slot: "L39+L40", venue: "SJT318", faculty: "SARAVANAN R", type: "LO" },
      { slot: "L27+L28", venue: "PRP234", faculty: "GOVINDA K", type: "LO" },
      { slot: "L21+L22", venue: "PRP231", faculty: "GAYATHRI P", type: "LO" },
      { slot: "L31+L32", venue: "PRP231", faculty: "MURALI S", type: "LO" },
      { slot: "L37+L38", venue: "PRP231", faculty: "KALAAVATHI B", type: "LO" },
      { slot: "L13+L14", venue: "PRP231", faculty: "VARALAKSHMI M", type: "LO" },
      { slot: "L19+L20", venue: "PRP231", faculty: "JENICKA S", type: "LO" },
      { slot: "L33+L34", venue: "PRP232", faculty: "JENICKA S", type: "LO" },
      { slot: "L43+L44", venue: "PRP232", faculty: "ATHIRA K", type: "LO" },
      { slot: "L19+L20", venue: "PRP232", faculty: "RAJA S P", type: "LO" },
      { slot: "L35+L36", venue: "PRP232", faculty: "RAJA S P", type: "LO" },
      { slot: "L45+L46", venue: "PRP232", faculty: "SHALINI L", type: "LO" },
      { slot: "L3+L4", venue: "PRP231", faculty: "KARTHIK G M", type: "LO" },
      { slot: "L47+L48", venue: "PRP231", faculty: "KARTHIK G M", type: "LO" },
      { slot: "L15+L16", venue: "PRP234", faculty: "ILANTHENRAL K P S K", type: "LO" },
      { slot: "L5+L6", venue: "PRP232", faculty: "ATHIRA K", type: "LO" },
      { slot: "L31+L32", venue: "PRP234", faculty: "ILANTHENRAL K P S K", type: "LO" },
      { slot: "L15+L16", venue: "PRP232", faculty: "SHALINI L", type: "LO" },
      { slot: "L57+L58", venue: "PRP231", faculty: "DURGESH KUMAR", type: "LO" },
      { slot: "L13+L14", venue: "PRP232", faculty: "SRIVANI A", type: "LO" },
      { slot: "L31+L32", venue: "PRP138", faculty: "ANURADHA G", type: "LO" },
      { slot: "L31+L32", venue: "PRP232", faculty: "SRIVANI A", type: "LO" },
      { slot: "L11+L12", venue: "PRP232", faculty: "ANURADHA G", type: "LO" },
      { slot: "L47+L48", venue: "PRP232", faculty: "JAGALINGAM P", type: "LO" },
      { slot: "L15+L16", venue: "PRP233", faculty: "JAGALINGAM P", type: "LO" },
      { slot: "L57+L58", venue: "PRP232", faculty: "VETRISELVI T", type: "LO" },
      { slot: "L7+L8", venue: "PRP232", faculty: "AYYASAMY.S", type: "LO" },
      { slot: "L1+L2", venue: "PRP232", faculty: "VETRISELVI T", type: "LO" },
      { slot: "L9+L10", venue: "PRP231", faculty: "SHARIEF BASHA S", type: "LO" },
      { slot: "L51+L52", venue: "PRP231", faculty: "SIVAPRASAD DARLA", type: "LO" },
      { slot: "L49+L50", venue: "PRP232", faculty: "NALLIAH M", type: "LO" },
      { slot: "L7+L8", venue: "PRP231", faculty: "PRAVEEN KUMAR G", type: "LO" },
      { slot: "L27+L28", venue: "PRP232", faculty: "KANAGARAJ K", type: "LO" },
      { slot: "L35+L36", venue: "PRP233", faculty: "ANINDITA KUNDU", type: "LO" },
      { slot: "L11+L12", venue: "PRP233", faculty: "SRIDHAR RAJ S", type: "LO" },
      { slot: "L43+L44", venue: "PRP233", faculty: "BERLIN M A", type: "LO" },
      { slot: "L1+L2", venue: "PRP233", faculty: "NITHYA N S", type: "LO" },
      { slot: "L19+L20", venue: "PRP233", faculty: "BADRINATH N", type: "LO" },
      { slot: "L31+L32", venue: "PRP233", faculty: "KANAGARAJ K", type: "LO" },
      { slot: "L3+L4", venue: "PRP233", faculty: "BERLIN M A", type: "LO" },
      { slot: "L5+L6", venue: "PRP233", faculty: "ANINDITA KUNDU", type: "LO" },
      { slot: "L45+L46", venue: "PRP233", faculty: "NITHYA N S", type: "LO" },
      { slot: "L33+L34", venue: "PRP233", faculty: "BADRINATH N", type: "LO" }
    ]
  },
  database: {
    theory: [
      { slot: "B2+TB2", venue: "SJT304", faculty: "DEEPA D", type: "TH" },
      { slot: "B2+TB2", venue: "SJT305", faculty: "SAURABH AGRAWAL", type: "TH" },
      { slot: "B1+TB1", venue: "SJT308", faculty: "DEEPIKA J", type: "TH" },
      { slot: "B2+TB2", venue: "SJT308", faculty: "DEEPIKA J", type: "TH" },
      { slot: "B1+TB1", venue: "SJT301", faculty: "SWATHI J.N", type: "TH" },
      { slot: "B1+TB1", venue: "SJT302", faculty: "MOHAN KUMAR P", type: "TH" },
      { slot: "B1+TB1", venue: "SJT715", faculty: "THANGARAMYA K", type: "TH" },
      { slot: "B2+TB2", venue: "SJT715", faculty: "THANGARAMYA K", type: "TH" },
      { slot: "B2+TB2", venue: "SJT301", faculty: "JOSHVA DEVADAS T", type: "TH" },
      { slot: "B2+TB2", venue: "SJT302", faculty: "MOHAN KUMAR P", type: "TH" },
      { slot: "B1+TB1", venue: "SJT305", faculty: "SAURABH AGRAWAL", type: "TH" },
      { slot: "B1+TB1", venue: "SJT712", faculty: "KONATHAM SUMALATHA", type: "TH" },
      { slot: "B2+TB2", venue: "SJT315", faculty: "KRISHNA RANI SAMAL K", type: "TH" },
      { slot: "B2+TB2", venue: "SJT323", faculty: "SARASWATHI PRIYADHARSHINI A", type: "TH" },
      { slot: "B1+TB1", venue: "SJT324", faculty: "SUDHAKAR K", type: "TH" },
      { slot: "B2+TB2", venue: "SJT401", faculty: "MAHESWARI B", type: "TH" },
      { slot: "B1+TB1", venue: "SJT409", faculty: "VASANTHI P", type: "TH" },
      { slot: "B1+TB1", venue: "SJT323", faculty: "SARASWATHI PRIYADHARSHINI A", type: "TH" },
      { slot: "B1+TB1", venue: "SJT415", faculty: "RAMANI S", type: "TH" },
      { slot: "B1+TB1", venue: "SJT403", faculty: "LYDIA JANE G", type: "TH" },
      { slot: "B1+TB1", venue: "SJT401", faculty: "MAHESWARI B", type: "TH" },
      { slot: "B1+TB1", venue: "SJT404", faculty: "NAGARAJA RAO A", type: "TH" },
      { slot: "B2+TB2", venue: "SJT404", faculty: "NAGARAJA RAO A", type: "TH" },
      { slot: "B2+TB2", venue: "SJT403", faculty: "LYDIA JANE G", type: "TH" },
      { slot: "B1+TB1", venue: "SJT402", faculty: "ILAYARAJA V", type: "TH" },
      { slot: "B2+TB2", venue: "SJT402", faculty: "ILAYARAJA V", type: "TH" },
      { slot: "B2+TB2", venue: "SJT324", faculty: "SUDHAKAR K", type: "TH" },
      { slot: "B1+TB1", venue: "SJT303", faculty: "ANAND BIHARI", type: "TH" },
      { slot: "B2+TB2", venue: "SJT303", faculty: "ANAND BIHARI", type: "TH" },
      { slot: "B2+TB2", venue: "SJT415", faculty: "RAMANI S", type: "TH" },
      { slot: "B1+TB1", venue: "SJT405", faculty: "AKILA VICTOR", type: "TH" },
      { slot: "B2+TB2", venue: "SJT405", faculty: "AKILA VICTOR", type: "TH" },
      { slot: "B2+TB2", venue: "SJT409", faculty: "ANITHA R", type: "TH" },
      { slot: "B1+TB1", venue: "SJT421", faculty: "ANUSHA R", type: "TH" },
      { slot: "B2+TB2", venue: "SJT421", faculty: "REVATHI C K", type: "TH" },
      { slot: "B1+TB1", venue: "SJT304", faculty: "DEEPA D", type: "TH" },
      { slot: "B1+TB1", venue: "SJT315", faculty: "KRISHNA RANI SAMAL K", type: "TH" },
      { slot: "B2+TB2", venue: "SJT712", faculty: "KONATHAM SUMALATHA", type: "TH" }
    ],
    lab: [
      { slot: "L25+L26", venue: "SJT622", faculty: "REVATHI C K", type: "LO" },
      { slot: "L45+L46", venue: "SJT416", faculty: "SWATHI J.N", type: "LO" },
      { slot: "L21+L22", venue: "SJT416", faculty: "JOSHVA DEVADAS T", type: "LO" },
      { slot: "L15+L16", venue: "SJT416", faculty: "MOHAN KUMAR P", type: "LO" },
      { slot: "L43+L44", venue: "SJT416", faculty: "MOHAN KUMAR P", type: "LO" },
      { slot: "L15+L16", venue: "SJT419", faculty: "RAMANI S", type: "LO" },
      { slot: "L25+L26", venue: "SJT416", faculty: "SUDHAKAR K", type: "LO" },
      { slot: "L13+L14", venue: "SJT416", faculty: "DEEPA D", type: "LO" },
      { slot: "L31+L32", venue: "SJT416", faculty: "AKILA VICTOR", type: "LO" },
      { slot: "L9+L10", venue: "SJT416", faculty: "AKILA VICTOR", type: "LO" },
      { slot: "L47+L48", venue: "SJT416", faculty: "SUDHAKAR K", type: "LO" },
      { slot: "L11+L12", venue: "SJT416", faculty: "DEEPIKA J", type: "LO" },
      { slot: "L41+L42", venue: "SJT416", faculty: "SAURABH AGRAWAL", type: "LO" },
      { slot: "L13+L14", venue: "SJT419", faculty: "THANGARAMYA K", type: "LO" },
      { slot: "L55+L56", venue: "SJT416", faculty: "THANGARAMYA K", type: "LO" },
      { slot: "L57+L58", venue: "SJT416", faculty: "DEEPA D", type: "LO" },
      { slot: "L27+L28", venue: "SJT622", faculty: "SAURABH AGRAWAL", type: "LO" },
      { slot: "L53+L54", venue: "SJT416", faculty: "DEEPIKA J", type: "LO" },
      { slot: "L45+L46", venue: "SJT621", faculty: "KONATHAM SUMALATHA", type: "LO" },
      { slot: "L47+L48", venue: "SJT419", faculty: "KRISHNA RANI SAMAL K", type: "LO" },
      { slot: "L27+L28", venue: "SJT416", faculty: "KONATHAM SUMALATHA", type: "LO" },
      { slot: "L27+L28", venue: "SJT419", faculty: "ANAND BIHARI", type: "LO" },
      { slot: "L9+L10", venue: "SJT419", faculty: "LYDIA JANE G", type: "LO" },
      { slot: "L43+L44", venue: "SJT418", faculty: "LYDIA JANE G", type: "LO" },
      { slot: "L53+L54", venue: "SJT418", faculty: "ILAYARAJA V", type: "LO" },
      { slot: "L25+L26", venue: "SJT419", faculty: "KRISHNA RANI SAMAL K", type: "LO" },
      { slot: "L43+L44", venue: "SJT419", faculty: "SARASWATHI PRIYADHARSHINI A", type: "LO" },
      { slot: "L25+L26", venue: "SJT418", faculty: "SARASWATHI PRIYADHARSHINI A", type: "LO" },
      { slot: "L55+L56", venue: "SJT419", faculty: "ANAND BIHARI", type: "LO" },
      { slot: "L11+L12", venue: "SJT419", faculty: "NAGARAJA RAO A", type: "LO" },
      { slot: "L53+L54", venue: "SJT419", faculty: "NAGARAJA RAO A", type: "LO" },
      { slot: "L29+L30", venue: "SJT419", faculty: "ILAYARAJA V", type: "LO" },
      { slot: "L1+L2", venue: "SJT416", faculty: "MAHESWARI B", type: "LO" },
      { slot: "L35+L36", venue: "SJT416", faculty: "VASANTHI P", type: "LO" },
      { slot: "L35+L36", venue: "SJT419", faculty: "ANUSHA R", type: "LO" },
      { slot: "L57+L58", venue: "SJT419", faculty: "MAHESWARI B", type: "LO" },
      { slot: "L7+L8", venue: "SJT416", faculty: "ANITHA R", type: "LO" },
      { slot: "L43+L44", venue: "SJT515", faculty: "RAMANI S", type: "LO" }
    ]
  },
  os: {
    theory: [
      { slot: "C2+TC2", venue: "SJT602A", faculty: "VENKATA LAKSHMI NARAYANA K", type: "TH" },
      { slot: "C1+TC1", venue: "SJT301", faculty: "ANISHA M. LAL", type: "TH" },
      { slot: "C2+TC2", venue: "SJT301", faculty: "VIJAYA KUMAR K", type: "TH" },
      { slot: "C1+TC1", venue: "SJT302", faculty: "RAJKUMAR S", type: "TH" },
      { slot: "C1+TC1", venue: "SJT303", faculty: "ANTO S", type: "TH" },
      { slot: "C2+TC2", venue: "SJT303", faculty: "ANTO S", type: "TH" },
      { slot: "C1+TC1", venue: "SJT304", faculty: "RUBY D", type: "TH" },
      { slot: "C2+TC2", venue: "SJT304", faculty: "RUBY D", type: "TH" },
      { slot: "C1+TC1", venue: "SJT305", faculty: "NAVEENKUMAR J", type: "TH" },
      { slot: "C2+TC2", venue: "SJT305", faculty: "NAVEENKUMAR J", type: "TH" },
      { slot: "C2+TC2", venue: "SJT308", faculty: "SURESH P", type: "TH" },
      { slot: "C1+TC1", venue: "SJT311", faculty: "THANUJA R", type: "TH" },
      { slot: "C2+TC2", venue: "SJT402", faculty: "SIVAPRAKASH S", type: "TH" },
      { slot: "C2+TC2", venue: "SJT404", faculty: "MOHANA SUNDARI L", type: "TH" },
      { slot: "C1+TC1", venue: "SJT308", faculty: "SURESH P", type: "TH" },
      { slot: "C1+TC1", venue: "SJT311A", faculty: "BHULAKSHMI BONTHU", type: "TH" },
      { slot: "C2+TC2", venue: "SJT315", faculty: "USHUS ELIZEBETH ZACHARIAH", type: "TH" },
      { slot: "C1+TC1", venue: "SJT323", faculty: "DEEPA.K", type: "TH" },
      { slot: "C2+TC2", venue: "SJT323", faculty: "DEEPA.K", type: "TH" },
      { slot: "C1+TC1", venue: "SJT324", faculty: "HITESHWAR KUMAR AZAD", type: "TH" },
      { slot: "C1+TC1", venue: "SJT401", faculty: "GLADYS GNANA KIRUBA B", type: "TH" },
      { slot: "C2+TC2", venue: "SJT401", faculty: "GLADYS GNANA KIRUBA B", type: "TH" },
      { slot: "C2+TC2", venue: "SJT405", faculty: "THIRUNAVUKKARASAN M", type: "TH" },
      { slot: "C2+TC2", venue: "SJT311", faculty: "THANUJA R", type: "TH" },
      { slot: "C2+TC2", venue: "SJT311A", faculty: "BHULAKSHMI BONTHU", type: "TH" },
      { slot: "C1+TC1", venue: "SJT315", faculty: "USHUS ELIZEBETH ZACHARIAH", type: "TH" },
      { slot: "C2+TC2", venue: "SJT324", faculty: "HITESHWAR KUMAR AZAD", type: "TH" },
      { slot: "C2+TC2", venue: "SJT302", faculty: "NIHA K", type: "TH" },
      { slot: "C1+TC1", venue: "SJT402", faculty: "SIVAPRAKASH S", type: "TH" },
      { slot: "C1+TC1", venue: "SJT403", faculty: "MALINI S", type: "TH" },
      { slot: "C2+TC2", venue: "SJT403", faculty: "MALINI S", type: "TH" },
      { slot: "C1+TC1", venue: "SJT404", faculty: "MOHANA SUNDARI L", type: "TH" },
      { slot: "C1+TC1", venue: "SJT405", faculty: "THIRUNAVUKKARASAN M", type: "TH" },
      { slot: "C1+TC1", venue: "SJT409", faculty: "GERALDINE BESSIE AMALI D", type: "TH" },
      { slot: "C1+TC1", venue: "SJT415", faculty: "PADMAVATHY T", type: "TH" },
      { slot: "C2+TC2", venue: "SJT415", faculty: "PADMAVATHY T", type: "TH" },
      { slot: "C2+TC2", venue: "SJT409", faculty: "GERALDINE BESSIE AMALI D", type: "TH" },
      { slot: "C1+TC1", venue: "SJT712", faculty: "MOHANKUMAR B", type: "TH" },
      { slot: "C2+TC2", venue: "SJT712", faculty: "MOHANKUMAR B", type: "TH" }
    ],
    lab: [
      { slot: "L57+L58", venue: "SJT318", faculty: "MOHANA SUNDARI L", type: "LO" },
      { slot: "L21+L22", venue: "SJT318", faculty: "GERALDINE BESSIE AMALI D", type: "LO" },
      { slot: "L31+L32", venue: "SJT318", faculty: "GERALDINE BESSIE AMALI D", type: "LO" },
      { slot: "L3+L4", venue: "SJT517", faculty: "PADMAVATHY T", type: "LO" },
      { slot: "L5+L6", venue: "SJT515", faculty: "VENKATA LAKSHMI NARAYANA K", type: "LO" },
      { slot: "L15+L16", venue: "SJT621", faculty: "MOHANKUMAR B", type: "LO" },
      { slot: "L37+L38", venue: "SJT317", faculty: "ANISHA M. LAL", type: "LO" },
      { slot: "L51+L52", venue: "SJT316", faculty: "PADMAVATHY T", type: "LO" },
      { slot: "L33+L34", venue: "SJT316", faculty: "MOHANKUMAR B", type: "LO" },
      { slot: "L33+L34", venue: "SJT318", faculty: "THIRUNAVUKKARASAN M", type: "LO" },
      { slot: "L19+L20", venue: "SJT316", faculty: "THIRUNAVUKKARASAN M", type: "LO" },
      { slot: "L19+L20", venue: "SJT318", faculty: "MOHANA SUNDARI L", type: "LO" },
      { slot: "L23+L24", venue: "SJT317", faculty: "SIVAPRAKASH S", type: "LO" },
      { slot: "L31+L32", venue: "SJT419", faculty: "SIVAPRAKASH S", type: "LO" },
      { slot: "L1+L2", venue: "SJT316", faculty: "MALINI S", type: "LO" },
      { slot: "L31+L32", venue: "SJT316", faculty: "MALINI S", type: "LO" },
      { slot: "L13+L14", venue: "SJT316", faculty: "NIHA K", type: "LO" },
      { slot: "L15+L16", venue: "SJT417", faculty: "HITESHWAR KUMAR AZAD", type: "LO" },
      { slot: "L33+L34", venue: "SJT319", faculty: "HITESHWAR KUMAR AZAD", type: "LO" },
      { slot: "L31+L32", venue: "SJT319", faculty: "GLADYS GNANA KIRUBA B", type: "LO" },
      { slot: "L21+L22", venue: "SJT319", faculty: "GLADYS GNANA KIRUBA B", type: "LO" },
      { slot: "L31+L32", venue: "SJT418", faculty: "DEEPA.K", type: "LO" },
      { slot: "L23+L24", venue: "SJT418", faculty: "DEEPA.K", type: "LO" },
      { slot: "L3+L4", venue: "SJT317", faculty: "USHUS ELIZEBETH ZACHARIAH", type: "LO" },
      { slot: "L49+L50", venue: "SJT317", faculty: "USHUS ELIZEBETH ZACHARIAH", type: "LO" },
      { slot: "L23+L24", venue: "SJT417", faculty: "BHULAKSHMI BONTHU", type: "LO" },
      { slot: "L33+L34", venue: "SJT417", faculty: "BHULAKSHMI BONTHU", type: "LO" },
      { slot: "L5+L6", venue: "SJT317", faculty: "THANUJA R", type: "LO" },
      { slot: "L51+L52", venue: "SJT317", faculty: "THANUJA R", type: "LO" },
      { slot: "L1+L2", venue: "SJT319", faculty: "SURESH P", type: "LO" },
      { slot: "L53+L54", venue: "SJT319", faculty: "SURESH P", type: "LO" },
      { slot: "L49+L50", venue: "SJT416", faculty: "ANTO S", type: "LO" },
      { slot: "L31+L32", venue: "SJT317", faculty: "RUBY D", type: "LO" },
      { slot: "L21+L22", venue: "SJT317", faculty: "RUBY D", type: "LO" },
      { slot: "L5+L6", venue: "SJT416", faculty: "ANTO S", type: "LO" },
      { slot: "L39+L40", venue: "SJT319", faculty: "RAJKUMAR S", type: "LO" },
      { slot: "L11+L12", venue: "SJT319", faculty: "VIJAYA KUMAR K", type: "LO" },
      { slot: "L5+L6", venue: "SJT419", faculty: "NAVEENKUMAR J", type: "LO" },
      { slot: "L51+L52", venue: "SJT319", faculty: "NAVEENKUMAR J", type: "LO" }
    ]
  },
  cloud: {
    theory: [
      { slot: "G1+TG1", venue: "SJT409", faculty: "ADRIJA BHATTACHARYA", type: "TH" },
      { slot: "G1+TG1", venue: "PRP575", faculty: "KAUSHIK HARIHARAN G", type: "TH" },
      { slot: "G2+TG2", venue: "SJT409", faculty: "KAUSHIK HARIHARAN G", type: "TH" },
      { slot: "G2+TG2", venue: "SJT521", faculty: "TAMILMANI A", type: "TH" },
      { slot: "G1+TG1", venue: "SJT301", faculty: "SUDHA.S", type: "TH" },
      { slot: "G2+TG2", venue: "SJT301", faculty: "CHELLATAMILAN T", type: "TH" },
      { slot: "G2+TG2", venue: "SJT302", faculty: "BALAKRISHNAN P", type: "TH" },
      { slot: "G1+TG1", venue: "SJT303", faculty: "ANNY LEEMA A", type: "TH" },
      { slot: "G1+TG1", venue: "SJT302", faculty: "JAYAKUMAR S", type: "TH" },
      { slot: "G2+TG2", venue: "SJT303", faculty: "ANNY LEEMA A", type: "TH" },
      { slot: "G1+TG1", venue: "SJT304", faculty: "ANUSHA N", type: "TH" },
      { slot: "G2+TG2", venue: "SJT304", faculty: "KARTHIK G M", type: "TH" },
      { slot: "G1+TG1", venue: "SJT305", faculty: "ARCHANA T", type: "TH" },
      { slot: "G2+TG2", venue: "SJT315", faculty: "YOGANAND S", type: "TH" },
      { slot: "G1+TG1", venue: "SJT323", faculty: "GOUTAM MAJUMDER", type: "TH" },
      { slot: "G2+TG2", venue: "PRP238", faculty: "SRIVANI A", type: "TH" },
      { slot: "G2+TG2", venue: "SJT323", faculty: "SHARMILA C", type: "TH" },
      { slot: "G1+TG1", venue: "SJT308", faculty: "BHUVANESWARI M", type: "TH" },
      { slot: "G1+TG1", venue: "SJT311", faculty: "CHANDRU VIGNESH C", type: "TH" },
      { slot: "G2+TG2", venue: "SJT311", faculty: "CHANDRU VIGNESH C", type: "TH" },
      { slot: "G1+TG1", venue: "SJT311A", faculty: "KRISHNA RANI SAMAL K", type: "TH" },
      { slot: "G1+TG1", venue: "SJT315", faculty: "YOGANAND S", type: "TH" },
      { slot: "G2+TG2", venue: "SJT324", faculty: "DHIVYAA C R", type: "TH" },
      { slot: "G1+TG1", venue: "SJT404", faculty: "MUTHUNAGAI S U", type: "TH" },
      { slot: "G2+TG2", venue: "SJT405", faculty: "DEEPA D", type: "TH" },
      { slot: "G1+TG1", venue: "SJT405", faculty: "BHAWANA TYAGI", type: "TH" },
      { slot: "G2+TG2", venue: "SJT311A", faculty: "UMAMAHESWARI M", type: "TH" },
      { slot: "G1+TG1", venue: "SJT324", faculty: "GAYATHRI S", type: "TH" },
      { slot: "G1+TG1", venue: "SJT422", faculty: "NAGA PRIYADARSINI R", type: "TH" },
      { slot: "G1+TG1", venue: "SJT415", faculty: "POOJA CHAUDHARY", type: "TH" },
      { slot: "G2+TG2", venue: "SJT415", faculty: "DIVIYA M", type: "TH" },
      { slot: "G2+TG2", venue: "SJT421", faculty: "SUNIL KUMAR", type: "TH" },
      { slot: "G2+TG2", venue: "SJT404", faculty: "KARTHIKA M S", type: "TH" },
      { slot: "G1+TG1", venue: "SJT421", faculty: "KONATHAM SUMALATHA", type: "TH" },
      { slot: "G1+TG1", venue: "SJT423", faculty: "MUKHTAR AHMAD SOFI", type: "TH" },
      { slot: "G2+TG2", venue: "SJT422", faculty: "SOUMYAJYOTI DEY", type: "TH" }
    ]
  },
  advcp: {
    theory: [
      { slot: "F1+TF1", venue: "SMV217", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "CDMM103", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "SMV217", faculty: "FACE (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "CDMM103", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "SJT224", faculty: "FACE (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "SJT223", faculty: "FACE (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "SJT222", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "SMV101", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "SJT222", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "SJT223", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "SMV101", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "SJT224", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "TT104", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "TT104", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "TT201", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "TT524", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "TT524", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "TT504", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "TT504", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "TT523", faculty: "FACE (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "TT523", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "TT530", faculty: "FACE (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "TT530", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "MB212", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "MB211", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "MB211", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "MB212", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "MB213", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "MB213", faculty: "FACE (APT)", type: "SS" },
      { slot: "F1+TF1", venue: "MB214", faculty: "FACE (APT)", type: "SS" },
      { slot: "F2+TF2", venue: "MB214", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT302", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT302", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT303", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT301", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT301", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT303", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT304", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT305", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT308", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT311", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT304", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT305", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT308", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT311", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT311A", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT315", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT324", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT401", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT311A", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT323", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT315", faculty: "ETHNUS (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT323", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT403", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT324", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT401", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT402", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT402", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT404", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT405", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT405", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT403", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT404", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT415", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT409", faculty: "FACE (APT)", type: "SS" },
      { slot: "E1+TE1", venue: "SJT415", faculty: "FACE (APT)", type: "SS" },
      { slot: "E2+TE2", venue: "SJT409", faculty: "FACE (APT)", type: "SS" }
    ]
  },
  compiler: {
    theory: [
      { slot: "A2+TA2", venue: "SJT305", faculty: "VISHNU PRIYA A", type: "TH" },
      { slot: "A1+TA1", venue: "SJT305", faculty: "VISHNU PRIYA A", type: "TH" },
      { slot: "A2+TA2", venue: "SJT308", faculty: "BHUVANESWARI M", type: "TH" },
      { slot: "A1+TA1", venue: "SJT308", faculty: "BHUVANESWARI M", type: "TH" },
      { slot: "E2+TE2", venue: "SJT617", faculty: "MUKHTAR AHMAD SOFI", type: "TH" },
      { slot: "E2+TE2", venue: "SJT602A", faculty: "SATHYA K", type: "TH" },
      { slot: "E1+TE1", venue: "SJT602", faculty: "SATHYA K", type: "TH" },
      { slot: "E1+TE1", venue: "SJT602A", faculty: "MUKHTAR AHMAD SOFI", type: "TH" },
      { slot: "A2+TA2", venue: "SJT303", faculty: "VISWANATHAN A", type: "TH" },
      { slot: "A1+TA1", venue: "SJT304", faculty: "KATARI BALAKRISHNA", type: "TH" },
      { slot: "A1+TA1", venue: "SJT301", faculty: "GOWTHAMI V", type: "TH" },
      { slot: "A2+TA2", venue: "SJT301", faculty: "BOOMINATHAN P", type: "TH" },
      { slot: "A1+TA1", venue: "SJT302", faculty: "KANNADASAN R", type: "TH" },
      { slot: "A2+TA2", venue: "SJT302", faculty: "KANNADASAN R", type: "TH" },
      { slot: "A1+TA1", venue: "SJT311", faculty: "KRISHNARAJ N", type: "TH" },
      { slot: "A2+TA2", venue: "SJT311", faculty: "KRISHNARAJ N", type: "TH" },
      { slot: "A1+TA1", venue: "SJT311A", faculty: "KANAGARAJ R", type: "TH" },
      { slot: "A2+TA2", venue: "SJT403", faculty: "MUTHUNAGAI S U", type: "TH" },
      { slot: "A1+TA1", venue: "SJT405", faculty: "ISLABUDEEN M", type: "TH" },
      { slot: "A2+TA2", venue: "SJT405", faculty: "ISLABUDEEN M", type: "TH" },
      { slot: "A1+TA1", venue: "SJT303", faculty: "VISWANATHAN A", type: "TH" },
      { slot: "A2+TA2", venue: "SJT311A", faculty: "KANAGARAJ R", type: "TH" },
      { slot: "A1+TA1", venue: "SJT323", faculty: "BASKARAN P", type: "TH" },
      { slot: "A2+TA2", venue: "SJT323", faculty: "BASKARAN P", type: "TH" },
      { slot: "A1+TA1", venue: "SJT324", faculty: "UMAMAHESWARI M", type: "TH" },
      { slot: "A2+TA2", venue: "SJT324", faculty: "UMAMAHESWARI M", type: "TH" },
      { slot: "A2+TA2", venue: "SJT402", faculty: "ARUMUGA ARUN R", type: "TH" },
      { slot: "A1+TA1", venue: "SJT403", faculty: "MUTHUNAGAI S U", type: "TH" },
      { slot: "A1+TA1", venue: "SJT401", faculty: "SABYASACHI KAMILA", type: "TH" },
      { slot: "A2+TA2", venue: "SJT401", faculty: "SABYASACHI KAMILA", type: "TH" },
      { slot: "A1+TA1", venue: "SJT402", faculty: "LAKSHMI S", type: "TH" },
      { slot: "A1+TA1", venue: "SJT404", faculty: "NIVITHA K", type: "TH" },
      { slot: "A2+TA2", venue: "SJT404", faculty: "NIVITHA K", type: "TH" },
      { slot: "A1+TA1", venue: "SJT409", faculty: "SUGANTHINI C", type: "TH" },
      { slot: "A1+TA1", venue: "SJT415", faculty: "NAGA PRIYADARSINI R", type: "TH" },
      { slot: "A2+TA2", venue: "SJT415", faculty: "NAGA PRIYADARSINI R", type: "TH" },
      { slot: "A1+TA1", venue: "SJT315", faculty: "BHAWANA TYAGI", type: "TH" },
      { slot: "A2+TA2", venue: "SJT315", faculty: "BHAWANA TYAGI", type: "TH" },
      { slot: "A2+TA2", venue: "SJT409", faculty: "SUGANTHINI C", type: "TH" },
      { slot: "A2+TA2", venue: "SJT304", faculty: "DEBI PRASANNA ACHARJYA", type: "TH" }
    ],
    lab: [
      { slot: "L15+L16", venue: "SJT418", faculty: "DEBI PRASANNA ACHARJYA", type: "LO" },
      { slot: "L9+L10", venue: "SJT515", faculty: "BOOMINATHAN P", type: "LO" },
      { slot: "L11+L12", venue: "SJT515", faculty: "KANNADASAN R", type: "LO" },
      { slot: "L39+L40", venue: "SJT515", faculty: "KANNADASAN R", type: "LO" },
      { slot: "L3+L4", venue: "SJT419", faculty: "VISHNU PRIYA A", type: "LO" },
      { slot: "L49+L50", venue: "SJT419", faculty: "VISHNU PRIYA A", type: "LO" },
      { slot: "L29+L30", venue: "SJT418", faculty: "BHUVANESWARI M", type: "LO" },
      { slot: "L49+L50", venue: "SJT418", faculty: "BHUVANESWARI M", type: "LO" },
      { slot: "L29+L30", venue: "SJT517", faculty: "UMAMAHESWARI M", type: "LO" },
      { slot: "L19+L20", venue: "SJT419", faculty: "KRISHNARAJ N", type: "LO" },
      { slot: "L55+L56", venue: "SJT418", faculty: "KRISHNARAJ N", type: "LO" },
      { slot: "L49+L50", venue: "SJT515", faculty: "UMAMAHESWARI M", type: "LO" },
      { slot: "L59+L60", venue: "SJT418", faculty: "KATARI BALAKRISHNA", type: "LO" },
      { slot: "L57+L58", venue: "SJT515", faculty: "LAKSHMI S", type: "LO" },
      { slot: "L57+L58", venue: "SJT418", faculty: "GOWTHAMI V", type: "LO" },
      { slot: "L3+L4", venue: "SJT515", faculty: "ARUMUGA ARUN R", type: "LO" },
      { slot: "L7+L8", venue: "SJT515", faculty: "VISWANATHAN A", type: "LO" },
      { slot: "L55+L56", venue: "SJT515", faculty: "VISWANATHAN A", type: "LO" },
      { slot: "L9+L10", venue: "SJT317", faculty: "KANAGARAJ R", type: "LO" },
      { slot: "L53+L54", venue: "SJT317", faculty: "KANAGARAJ R", type: "LO" },
      { slot: "L41+L42", venue: "SJT621", faculty: "BASKARAN P", type: "LO" },
      { slot: "L49+L50", venue: "SJT622", faculty: "MUTHUNAGAI S U", type: "LO" },
      { slot: "L21+L22", venue: "SJT515", faculty: "NIVITHA K", type: "LO" },
      { slot: "L55+L56", venue: "SJT517", faculty: "NAGA PRIYADARSINI R", type: "LO" },
      { slot: "L29+L30", venue: "SJT516", faculty: "SUGANTHINI C", type: "LO" },
      { slot: "L39+L40", venue: "SJT622", faculty: "SUGANTHINI C", type: "LO" },
      { slot: "L19+L20", venue: "SJT621", faculty: "NAGA PRIYADARSINI R", type: "LO" },
      { slot: "L47+L48", venue: "SJT515", faculty: "BHAWANA TYAGI", type: "LO" },
      { slot: "L41+L42", venue: "SJT622", faculty: "SABYASACHI KAMILA", type: "LO" },
      { slot: "L21+L22", venue: "SJT621", faculty: "SABYASACHI KAMILA", type: "LO" },
      { slot: "L25+L26", venue: "SJT515", faculty: "BHAWANA TYAGI", type: "LO" },
      { slot: "L25+L26", venue: "SJT621", faculty: "BASKARAN P", type: "LO" },
      { slot: "L47+L48", venue: "SJT516", faculty: "ISLABUDEEN M", type: "LO" },
      { slot: "L23+L24", venue: "SJT621", faculty: "ISLABUDEEN M", type: "LO" },
      { slot: "L43+L44", venue: "SJT621", faculty: "SATHYA K", type: "LO" },
      { slot: "L1+L2", venue: "SJT418", faculty: "MUKHTAR AHMAD SOFI", type: "LO" },
      { slot: "L43+L44", venue: "SJT622", faculty: "MUKHTAR AHMAD SOFI", type: "LO" },
      { slot: "L3+L4", venue: "SJT418", faculty: "SATHYA K", type: "LO" },
      { slot: "L37+L38", venue: "SJT516", faculty: "NIVITHA K", type: "LO" },
      { slot: "L11+L12", venue: "SJT317", faculty: "MUTHUNAGAI S U", type: "LO" }
    ]
  },
  ai: {
    theory: [
      { slot: "D2+TD2", venue: "SJT323", faculty: "JAYASHREE J", type: "TH" },
      { slot: "G2+TG2", venue: "SJT423", faculty: "JYOTISMITA CHAKI", type: "TH" },
      { slot: "G2+TG2", venue: "SJT424", faculty: "MADHURI W", type: "TH" },
      { slot: "D1+TD1", venue: "SJT405", faculty: "AKILA VICTOR", type: "TH" },
      { slot: "D1+TD1", venue: "SJT301", faculty: "VISWANATHAN P", type: "TH" },
      { slot: "D2+TD2", venue: "SJT302", faculty: "MOHAN KUMAR P", type: "TH" },
      { slot: "D1+TD1", venue: "SJT303", faculty: "MARIAPPAN R", type: "TH" },
      { slot: "D2+TD2", venue: "SJT303", faculty: "ANNAPURNA JONNALAGADDA", type: "TH" },
      { slot: "D1+TD1", venue: "SJT304", faculty: "SHASHANK MOULI SATAPATHY", type: "TH" },
      { slot: "D1+TD1", venue: "SJT302", faculty: "ILANTHENRAL K P S K", type: "TH" },
      { slot: "D1+TD1", venue: "SJT315", faculty: "NAVAMANI T M", type: "TH" },
      { slot: "D2+TD2", venue: "SJT315", faculty: "NAVAMANI T M", type: "TH" },
      { slot: "D1+TD1", venue: "SJT323", faculty: "ANTO S", type: "TH" },
      { slot: "D1+TD1", venue: "SJT311", faculty: "GERALDINE BESSIE AMALI D", type: "TH" },
      { slot: "D2+TD2", venue: "SJT324", faculty: "EBENEZER JULIET S", type: "TH" },
      { slot: "D2+TD2", venue: "SJT715", faculty: "JAYA SUBALAKSHMI R", type: "TH" },
      { slot: "D1+TD1", venue: "SJT402", faculty: "TAMIZHARASI T", type: "TH" },
      { slot: "D1+TD1", venue: "SJT415", faculty: "JAGALINGAM P", type: "TH" },
      { slot: "D1+TD1", venue: "SJT324", faculty: "SUDARSHAN NANDY", type: "TH" },
      { slot: "D2+TD2", venue: "SJT301", faculty: "ANAND BIHARI", type: "TH" },
      { slot: "D2+TD2", venue: "SJT305", faculty: "MOHANA CM", type: "TH" },
      { slot: "D1+TD1", venue: "SJT308", faculty: "ATHIRA K", type: "TH" },
      { slot: "D2+TD2", venue: "SJT311", faculty: "DILIPKUMAR S", type: "TH" },
      { slot: "D1+TD1", venue: "SJT401", faculty: "THAMIZHARASAN S", type: "TH" },
      { slot: "D1+TD1", venue: "SJT403", faculty: "KOPPERUNDEVI N", type: "TH" },
      { slot: "D2+TD2", venue: "SJT404", faculty: "KOVENDAN A.K.P", type: "TH" },
      { slot: "D1+TD1", venue: "SJT607", faculty: "KAMANASISH BHATTACHARJEE", type: "TH" },
      { slot: "D2+TD2", venue: "SJT409", faculty: "MOHANA SUNDARI L", type: "TH" },
      { slot: "D1+TD1", venue: "SJT514", faculty: "MALATHI M", type: "TH" },
      { slot: "D2+TD2", venue: "SJT514", faculty: "RAJAY VEDARAJ I.S", type: "TH" },
      { slot: "D1+TD1", venue: "SJT601", faculty: "JEEVANANTHAM A.K.", type: "TH" },
      { slot: "D2+TD2", venue: "SJT601", faculty: "THIRUMOORTHY K.", type: "TH" },
      { slot: "D1+TD1", venue: "SJT602A", faculty: "VIJAYANAND C", type: "TH" },
      { slot: "D2+TD2", venue: "SJT304", faculty: "VIJAYASHREE J", type: "TH" },
      { slot: "D1+TD1", venue: "SJT305", faculty: "SRIDHAR RAJ S", type: "TH" },
      { slot: "D1+TD1", venue: "SJT311A", faculty: "DURGESH KUMAR", type: "TH" },
      { slot: "D2+TD2", venue: "SJT308", faculty: "DURGESH KUMAR", type: "TH" },
      { slot: "D2+TD2", venue: "SJT403", faculty: "KARTHIK K", type: "TH" },
      { slot: "D2+TD2", venue: "SJT407", faculty: "SRI PREETHAA K R", type: "TH" },
      { slot: "D2+TD2", venue: "SJT415", faculty: "SARASWATHI PRIYADHARSHINI A", type: "TH" },
      { slot: "G2+TG2", venue: "SJT308", faculty: "SIVAKUMAR V", type: "TH" },
      { slot: "D2+TD2", venue: "SJT619", faculty: "ARIVARASU M", type: "TH" },
      { slot: "D1+TD1", venue: "SJT617", faculty: "SUKANTA GHOSH", type: "TH" },
      { slot: "D2+TD2", venue: "SJT626", faculty: "JUSTIN GOPINATH A", type: "TH" }
    ]
  }
};

export default facultyData;